#![allow(unknown_lints)]
#![allow(clippy::derive_partial_eq_without_eq)]

use std::str::FromStr;

#[derive(Debug)]
pub enum Error {
    ParseError,
}

impl From<()> for Null {
    fn from(_: ()) -> Self {
        Self {}
    }
}

impl FromStr for NvmeAnaState {
    type Err = Error;
    fn from_str(state: &str) -> Result<Self, Self::Err> {
        match state {
            "optimized" => Ok(Self::NvmeAnaOptimizedState),
            "non_optimized" => Ok(Self::NvmeAnaNonOptimizedState),
            "inaccessible" => Ok(Self::NvmeAnaInaccessibleState),
            _ => Err(Error::ParseError),
        }
    }
}

// Include Rust sources generated by protobuf.
#[cfg(target_os = "linux")]
include!(concat!(env!("OUT_DIR"), "/mayastor.rs"));

// In order to IDE to work properly with protobuf definitions on non-Linux platform,
// one can copy generated bindings (mayastor.rs) from a Linux target and put them
// to .pregenerated directory.
// This has to be done every time Mayastor API V0 is changed.
#[cfg(not(target_os = "linux"))]
mod v0_generated {
    include!("../.pregenerated/mayastor.rs");
}

#[cfg(not(target_os = "linux"))]
pub use v0_generated::*;
