[package]
name = "devinfo"
version = "1.0.0"
edition = "2018"

[dependencies]
nix = { workspace = true, default-features = false, features = ["feature"] }
semver = { workspace = true }
snafu = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
[build-dependencies]
bindgen = { workspace = true }

[target.'cfg(target_os="linux")'.dependencies]
udev = { workspace = true }
