[package]
name = "secret-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "rt-multi-thread"] }
k8s-openapi = { workspace = true }
kube = { workspace = true, features = ["derive", "runtime"] }
platform = { path = "../platform" }
snafu = { workspace = true }
tracing = { workspace = true }

[[example]]
name = "secret-provider-example"
path = "examples/src/main.rs"
