[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "secret_provider"
path = "src/main.rs"

[dependencies]
secret-provider = { path = "../../secret_provider"}
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread"] }
kube = { version = "0.94.2", features = ["derive", "runtime"] }