syntax = "proto3";

package mayastor.v1;
// Protocol over which the bdev/replica/nexus etc will be shared.
enum ShareProtocol {
  NONE = 0; // not exposed
  NVMF = 1; // NVMe over Fabrics (TCP)
  ISCSI = 2; // iSCSI
}

message MayastorFeatures {
  // NVMe ANA enablement status.
  bool asymmetricNamespaceAccess = 1;
  // LVM backend presence and enablement status.
  optional bool logicalVolumeManager = 2;
  // SnapshotRebuild presence and enablement status.
  optional bool snapshotRebuild = 3;
  // RDMA support for Mayastor nvmf target.
  optional bool rdmaCapableIoEngine = 4;
}

message MayastorBugFixes {
  // Nexus rebuilds both the clusters allocated to the replica and its ancestors clusters
  bool nexusRebuildReplicaAncestry = 1;
}

// Cipher to use for encryption.
enum Cipher {
  AES_CBC = 0;
  AES_XTS = 1;
}

// Represents an encryption key that can be used to encrypt an
// entity like pool or lvol/replica.
message EncryptionKey {
  // Name of the key.
  string key_name = 1;
  // The AES encryption key.
  bytes key = 2;
  // AES Key length.
  uint32 key_length = 3;
  // key2 (required for AES_XTS).
  optional bytes key2 = 4;
  // The length of key2. Must be same as key_length.
  optional uint32 key2_length = 5;
}

message EncryptionData {
  // Cipher to be used.
  Cipher cipher = 1;
  // The encryption key.
  EncryptionKey key = 2;
}

// This message represents name of the source for getting
// key parameter details.
message EncryptionSecret {
  string secret = 1;
}
