
syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";
import "common.proto";

package mayastor.v1;

service PoolRpc {
  // Storage pool related methods.
  //
  // Storage pool is made up of block devices disks and provides a storage
  // space for provisioning of replicas.
  rpc CreatePool (CreatePoolRequest) returns (Pool) {}
  rpc DestroyPool (DestroyPoolRequest) returns (google.protobuf.Empty) {}
  rpc ExportPool (ExportPoolRequest) returns (google.protobuf.Empty) {}
  rpc ImportPool (ImportPoolRequest) returns (Pool) {}

  rpc ListPools (ListPoolOptions) returns (ListPoolsResponse) {}

  rpc GrowPool (GrowPoolRequest) returns (GrowPoolResponse) {}
  rpc GrowPoolV2 (GrowPoolRequest) returns (Pool) {}

  // Clear error counters and alerts
  rpc ClearErrors (ClearErrorRequest) returns (Pool) {}

  // Pool disk probing
  rpc ProbePool(ProbePoolRequest) returns (ProbePoolResponse) { }
}

// Specifies the type of the pool
enum PoolType {
  Lvs = 0;  // pool backed by spdk lvs
  Lvm = 1;  // pool backed by lvm vg
}

// The wrapper for pooltype.
// It helps in defining optional fields
// when required.
message PoolTypeValue {
  PoolType value = 1;
}

// Create pool arguments.
message CreatePoolRequest {
  // Name of the pool.
  string name = 1;
  // Optional uuid for the pool to be created.
  google.protobuf.StringValue uuid = 2;
  // Disk device paths or URIs to be claimed by the pool.
  repeated string disks = 3;
  // Type of the pool.
  PoolType pooltype = 4;
  // Default cluster size is 4MiB (4 * 1024 * 1024), input cluster size must be in "bytes" but
  // must be multiple of 1MiB, else default cluster size i.e 4MiB will be considered. Minimum
  // cluster size can be input as 1048576 (1024 * 1024) bytes (1MiB)
  optional uint32 cluster_size = 5;
  // Optional pool metadata arguments.
  optional PoolMetadataArgs md_args = 6;
  // Encryption parameters for this pool. Either as raw key params, OR a name to a Kubernetes
  // Secret resource or a file.
  oneof encryption {
    EncryptionData data = 7;
    EncryptionSecret secret = 8;
  }
}

// Pool metadata arguments.
message PoolMetadataArgs {
  // Deprecated after the addition of max_expansion.
  optional float md_resv_ratio = 1;
  // This defines how much a Pool can grow upto.
  // Reserves metadata during pool creation to support required growth.
  // There are 2 ways in which this can be set.
  //
  // 1. Using factor
  // 1x will allow limited growth. pool cannot grow upto 2x the original size.
  // 5x will allow the pool to be grown 5 times the initial size.
  //
  // 2. Absolute size
  // User can pass Absolute size. For example, 800GiB, 3.5TiB or 4563726394B.
  //
  optional string max_expansion = 2;
}

// Create pool arguments.
message ImportPoolRequest {
  string name = 1;           // name of the pool
  google.protobuf.StringValue uuid = 2; // optional uuid for the pool to be imported
  repeated string disks = 3; // disk device paths or URIs to be claimed by the pool
  PoolType pooltype = 4;     // type of the pool
  // Encryption parameters for this pool. Either as raw key params, OR a name to a Kubernetes
  // Secret resource or a file.
  oneof encryption {
    EncryptionData data = 5;
    EncryptionSecret secret = 6;
  }
}

// State of the storage pool (terminology comes from ZFS).
enum PoolState {
  POOL_UNKNOWN = 0;
  POOL_ONLINE = 1;   // the pool is in normal working order
  POOL_DEGRADED = 2; // the pool has experienced a failure but can still function
  POOL_FAULTED = 3;  // the pool is completely inaccessible
  POOL_SUSPECTED = 4; // the pool is suspected to have some issues due to warning alerts
}

// Storage pool properties
message Pool {
  // UUID of the storage pool.
  string uuid = 1;
  // Name of the storage pool.
  string name = 2;
  // Absolute path(s) of disk devices which are claimed by the pool.
  repeated string disks = 3;
  // Current state of the storage pool.
  PoolState state = 4;
  // Pool capacity in bytes available for user data.
  uint64 capacity = 5;
  // Storage capacity in bytes allocated for storing user data.
  uint64 used = 6;
  // Type of the pool.
  PoolType pooltype = 7;
  // Committed size of all pool's replicas: a sum of capacities of all replicas.
  uint64 committed = 8;
  // Cluster size in bytes. It defines the allocation granularity for replicas
  // and snapshots. Cluster size can set during pool creation.
  uint32 cluster_size = 9;
  // Page size in bytes. This is the write and read granularity.
  optional uint32 page_size = 10;
  // Usable capacity of the pool's underlying storage device(s).
  // It changes when the device's capacity changes.
  // This value is equal or large than the current pool capacity. If it is larger,
  // pool can be grown to fill the entire device's capacity.
  // If the pool backend does not support disk capacity evaluation, zero is returned.
  uint64 disk_capacity = 11;
  // Optional pool metadata info.
  optional PoolMetadataInfo md_info = 12;
  // Is the pool encrypted.
  optional bool encrypted = 13;
  // Maximum capacity upto which this pool can be expanded, in bytes.
  optional uint64 max_expandable_size = 14;
  // Information for each pool disk.
  repeated DiskInfo disk_info = 15;
  // Error information at the pool top-level.
  optional PoolErrors errors = 16;
}

// Pool metadata info.
message PoolMetadataInfo {
  // Size of metadata allocation page in bytes.
  uint32 md_page_size = 1;
  // Number of metadata pages reserved on the pool for storing replica metadata.
  // Metadata reservation capacity can be a limiting factor for the number
  // of replicas and snaphots a pool can accommodate.
  // Depending on the pool backend, this value can be defined on pool creation,
  // or can dynamically change.
  // If the pool backend does not support metadata capacity evaluation, zero is returned.
  uint64 md_pages = 2;
  // Number of metadata pages used for storing metadata for the currently
  // existing replicas.
  // If the pool backend does not support metadata capacity evaluation, zero is returned.
  uint64 md_used_pages = 3;
}

// Destroy pool arguments.
message DestroyPoolRequest {
  string name = 1;  // name of the pool
  google.protobuf.StringValue uuid = 2; // optional uuid for the pool to be destroyed
}

// Export pool arguments.
message ExportPoolRequest {
  string name = 1;  // name of the pool
  google.protobuf.StringValue uuid = 2; // optional uuid for the pool to be exported
}

// List of pools and their properties.
message ListPoolsResponse {
  repeated Pool pools = 1;  // list of the pools
}

message ListPoolOptions {
  google.protobuf.StringValue name = 1; // list the pools matching the name if provided
  PoolTypeValue pooltype = 2; // optional pooltype filter
  google.protobuf.StringValue uuid = 3; // get the pool matching the uuid if provided
}

// Grow pool arguments.
message GrowPoolRequest {
  string name = 1;                        // name of the pool
  google.protobuf.StringValue uuid = 2;   // optional uuid for the pool to be grown
}

// Grow pool response.
message GrowPoolResponse {
  // Pool's state before expansion.
  Pool previous_pool = 1;
  // Pool's state after expansion.
  // The difference between previous_pool and current_pool can be used
  // to determine how much the pool has grown, and if the growth
  // actually occurred.
  Pool current_pool = 2;
}

message PoolErrors {
  // These are generated from the below metrics
  PoolAlerts                    alerts = 1;

  // Disk IO errors
  uint64                io_error_count = 2;
  uint64            io_error_threshold = 3;

  // Disk IO stalls
  bool                      io_stalled = 4;
  uint64     io_stall_transition_count = 5;
  uint64 io_stall_transition_threshold = 6;
}

message PoolAlerts {
  PoolAlertStatus       status = 1;

  // No status alerts are raised
  repeated PoolAlert    notice = 2;
  repeated PoolAlert attention = 3;
  // Warnings downgrades the pool state to Suspected
  repeated PoolAlert   warning = 4;
  // Pools with critical alerts should not be used
  repeated PoolAlert  critical = 5;
}

enum PoolAlertStatus {
  // No issues detected; pool is operating normally
  Healthy   = 0;

  // Non‑critical issues present; user attention is recommended
  Attention = 1;

  // Conditions have exceeded warning thresholds (fixed or based on trends over a defined time window)
  Warning   = 2;

  // Severe issues detected; pool usage should be avoided
  Critical  = 3;
}

enum PoolAlert {
  // Unrecognized or unsupported alert type
  Unknown                = 0;

  // Pool I/O is currently stalled
  IoStalled              = 1;

  // I/O is not stalled as of now, but stalls have occurred over a defined time window
  IoStallIntermittent    = 2;

  // I/O is not stalled as of now, but stalls have occurred too frequently over a defined time window
  IoStallIntermittentExc = 3;

  // I/O errors have been detected for the pool
  IoError                = 4;

  // I/O errors exceed defined thresholds
  IoErrorExc             = 5;
}

message DiskInfo {
  // The disk uri used to open the disk
  string uri = 1;
  // Errors seen for this disk
  PoolErrors errors = 2;
}

message ClearErrorRequest {
  // Name of the pool
  string          name = 1;
  // Uuid of the pool
  optional string uuid = 2;

  // If one or more disks is specified, only those errors associated with the specified disk or disks are cleared.
  repeated string disks = 3;

  // Error clearing request
  ClearErrors clear = 4;
}

enum ClearErrors {
  // Clears all counted errors and stall transitions
  // Note: It doesn't clear an io stall state if the pool is currently in a stalled state.
  // The stall state will be cleared when the pool is no longer stalled.
  ClearAll = 0;
  // Clears only the counted I/O errors
  ClearIoErrors = 1;
  // Clears only the I/O stall transition count
  ClearIoStallTransitions = 2;
}

// Probe disks for pool create/import readiness.
// This RPC should try very hard not to fail and rather succeed with information about the probe errors it found.
// Also no error messages related to this probing should be displayed to avoid polluting the logs.
// Errors
// This RPC may fail with `ALREADY_EXISTS` if the pool is already loaded and the disks match the request.
message ProbePoolRequest {
  ImportPoolRequest request = 1;

  // Probing for import or creation (ie null or malloc import may not apply for import)
  bool import = 2;

  // The requested completeness probes.
  // Disk presence probe is always implicitly performed and cannot be disabled.
  optional PoolProbes probes = 3;
}

message PoolProbes {
  // Issue a Read IO to the pool/disks and check for success within short timeout.
  bool          test_read = 1;
  // Read must complete within this amount of time for a success.
  uint64        test_read_tmo_secs = 2;

  // Read pool super-block and check for its validity.
  bool          validate_sb = 3;
}

message ProbeDiskInfo {
  // A disk specified for probing.
  string disk = 1;

  // Any errors found by the probe.
  repeated ProbeError error = 2;
}

message ProbeError {
  // A value representing the encountered error.
  ProbeErrorCode code = 1;
  // Additional information as human readable.
  optional string msg = 2;
}

enum ProbeErrorCode {
  // It's an unknown error, we don't have a valid code for it.
  ProbeUnknown = 0;
  // The Disk was not found in the system.
  DiskNotFound = 1;
  // If the Disk is already claimed by something.
  // This may happen if the disk is used by another pool for example.
  DiskClaimed = 2;
  // PCI driver not supported.
  PCIDriverUnsupported = 3;
  // PCI still bound to kernel nvme driver.
  PCIKernelBound = 4;
  // PCI BDF exists but it's not an NVMe device.
  PCINotNvme = 5;
  // Disk read I/O errors.
  DiskReadIoError = 6;
  // The disk URI is invalid or not supported.
  InvalidDiskUri = 7;
  // Pool on-disk name doesn't match the expected value.
  ForeignPoolName = 8;
  // Pool on-disk uuid doesn't match the expected value.
  ForeignPoolUid = 9;
  // I/O error encountered when trying to read the pool super block.
  SuperBlockIoError = 10;
  // Invalid super block (eg: CRC error, likely metadata corruption).
  InvalidSuperBlock = 11;
  // Disk is not importable (ie malloc).
  DiskNotImportable = 12;
  // Probing is not implemented for this URI.
  UriNotHandled = 13;
}

message PoolProbeMeta {
  // The name of the pool found in the specified disks (if any).
  string name = 1;
  // The uuid of the pool found in the specified disks.
  string uuid = 2;
}

message ProbePoolResponse {
  // Specified probes found no issues.
  bool success = 1;
  // The probes which were actually performed.
  // This is useful for compatibility, as the server may not support
  // all the requested probes.
  PoolProbes probed = 2;

  // If super block was read successfully, this is its info.
  PoolProbeMeta metadata = 3;

  // All the probe errors (per disk).
  map<string,ProbeDiskInfo> errors = 4;
}
