[package]
name = "event-publisher"
version = "0.1.0"
edition = "2021"

[features]
default = ["rls-aws-lc-rs"]
rls-aws-lc-rs = ["events-api/rls-aws-lc-rs"]

[dependencies]
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tokio = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
events-api = { path = "../apis/events", default-features = false }
