[package]
name = "event-publisher"
version = "0.1.0"
edition = "2021"

[features]
default = ["rls-ring"]
rls-aws-lc-rs = ["events-api/rls-aws-lc-rs"]
rls-ring = ["events-api/rls-ring"]

[dependencies]
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tokio = { version = "1.41.0" }
tracing = "0.1.40"
serde_json = "1.0.132"
events-api = { path = "../apis/events", default-features = false }
