[package]
name = "events-api"
version = "0.1.0"
edition = "2021"


[build-dependencies]
tonic-build = "0.12.3"

[features]
default = ["rls-ring"]
rls-aws-lc-rs = ["async-nats/aws-lc-rs"]
rls-ring = ["async-nats/ring"]

[dependencies]
async-nats = { version = "0.37.0", default-features = false }
bytes = "1.8.0"
serde = "1.0.214"
serde_json = "1.0.132"
tokio = "1.41.0"
tracing = "0.1.40"
uuid = { version = "1.11.0", features = ["v4"] }
async-trait = "0.1.83"
futures = "0.3.31"
snafu = "0.8.5"
tonic = "0.12.3"
prost = "0.13.3"
chrono = "0.4.38"
once_cell = "1.20.2"
prost-extend = { path = "../../prost-extend" }
