[package]
name = "events-api"
version = "0.1.0"
edition = "2021"


[build-dependencies]
tonic-build = { workspace = true }

[features]
default = ["rls-aws-lc-rs"]
rls-aws-lc-rs = ["async-nats/aws-lc-rs"]

[dependencies]
async-nats = { workspace = true, default-features = false }
bytes = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
async-trait = { workspace = true }
futures = { workspace = true }
snafu = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
chrono = { workspace = true }
prost-extend = { path = "../../prost-extend" }
