[package]
name = "io-engine-api"
version = "1.0.0"
edition = "2021"

[build-dependencies]
tonic-build = { workspace = true }
prost-build = { workspace = true }

[dependencies]
tonic = { workspace = true }
bytes = { workspace = true }
prost = { workspace = true }
prost-derive = { workspace = true }
prost-extend = { path = "../../prost-extend" }
prost-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
