[package]
name = "composer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true, features = ["full"] }
futures = { workspace = true }
tracing = { workspace = true }
once_cell = { workspace = true }
ipnetwork = { workspace = true }
bollard = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
