[package]
name = "nvmeadm"
version = "1.0.0"
edition = "2021"

[dependencies]
derive_builder = "0.20.2"
enum-primitive-derive = "0.3.0"
glob = { workspace = true }
ioctl-gen = "0.1.1"
libc = "0.2.161"
nix = { workspace = true, default-features = false, features = ["ioctl"] }
num-traits = "0.2.19"
once_cell = { workspace = true }
snafu = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
url = { workspace = true }
