name: Lint Commit Messages
on:
  merge_group:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
    branches:
      - staging

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install CommitLint and Dependencies
        run: npm install @commitlint/config-conventional @commitlint/cli
      - name: Lint Commits
        run: |
          # Only run for PR's and simply succeed the bors staging branch
          if [ ! ${{ github.ref }} = "refs/heads/staging" ]; then
            first_commit=${{ github.event.pull_request.base.sha }}
            last_commit=${{ github.event.pull_request.head.sha }}
            npx commitlint --from $first_commit --to $last_commit -V
          fi
