# Based on https://github.com/hyperledger/besu/pull/5207/files
name: DCO
on:
  merge_group:

jobs:
  DCO:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - run: echo "This DCO job runs on merge_queue event and doesn't check PR contents"
