name: Code Linter
on:
  merge_group:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
jobs:
  rustlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - name: nix-shell
        run: nix-shell --pure --run exit
      - name: cargo-fmt
        run: nix-shell --run ./scripts/rust/linter.sh
      - name: cargo-clippy
        run: nix-shell --run ./scripts/rust/style.sh
